### ISSUE TITLE
添加README文件

### ISSUE THREAD

**Issue by JamesCao2048** [linxuyalun/devops#1]
添加README文件
包括
- 一个想法的Proposal
- 系统架构及实现相关
- Usage：如何配置本项目所需环境及运行示例

**Comment by pengy14** [comment]
## idea
我们小组目前想法是做一个平台，监听各种降价促销的商品 ，帮助用户低价买到自己想要的东西。
* 基本的逻辑是： 用户添加想要监听的商品->监听->邮件通知。
* 基本架构：前后端分离
* 技术框架：react+nodejs+mongodb
