### ISSUE TITLE
配置CI和CD环境

### ISSUE THREAD

**Issue by JamesCao2048** [linxuyalun/devops#2]
包括

- CI: Continuous Integration.
- CD: Continuous Delievery.

**Comment by linxuyalun** [comment]
在这次项目中打算使用的CI/CD工具是**Drone**，一个问题是为什么选择**Drone**而不选择**Jenkins**，在这里做一些解释：
Jenkins本身作为一个老牌的CI/CD工具是一开始CI/CD工具的选择，但是在进行一定的了解学习后，Jenkins存在这样一些问题：
* 不管是使用什么样的语言构建完一个项目后，如果使用这个项目，首先需要给这个项目安装众多的Plugin，包含`git clone`，depoly，notification等，非常复杂；
* Jenkins是一个基于java的工具，如果要修改Jenkins里的Plugin，只能使用Java，当然在这次的项目里我们应该不至于去修改Plugin，这里将其列出是为了和后面的Drone比较；
* Jenkins的设定比较复杂，如果一段时间不用以后基本完全遗忘。

选择Drone主要基于以下优势：
* Drone是用Go语言编写的，所以启动速度很快，并且启动Drone后占用内存很小；
* Drone不需要管理者，Drone的所有的管理动作都是通过`.drone.yml`文件进行控制，也就是说只要有Drone的读写权限，团队只需要学习如何去写这个文件即可控制项目的持续集成和持续部署，学习成本低，适合本项目；
* Drone支持多版本编译；
* Drone对k8s支持良好；
* Drone完全基于container开发，因此项目之间互相不会干扰，同样的，因为Drone完全基于container，任何语言都可以写Plugin，也就是说，假设我现在用java构建了一个plugin，我把它打包进docker后放到dockerhub，之后大家都可以使用我这个plugin而不需要关注这个plugin是用什么语言写的，这一点是Jenkins无法比拟的。
